### ISSUE TITLE
iOS seems to load the images every time whereas Android caches them as expected

### ISSUE THREAD

**Issue by rodneyjoyce** [zyra/ionic-image-loader#105]
Hello,

Great component! It is working fine on Android when I do a native build however when I do a native build on iOS the images load every time. When I go back to the page the images reload - ie. it does not seem to cache the images on IOS (iPhone 6S+ and iOS 10.3).

Has anyone else had this problem?

**Comment by fdambrosio** [comment]
Hi, so it's not working on IOS?

**Comment by rodneyjoyce** [comment]
Yes, it does not work as expected - ie. it is not caching the images like it does on Android

**Comment by glemiere** [comment]
Same problem here.

**Comment by glemiere** [comment]
In my case it was because I was using Base64. What we're seeing is probably the time required to process the Base64 data to be processed.

**Comment by matthieu80** [comment]
@glemiere is right, i had the same problem until i comment out:
imageLoaderConfig.setImageReturnType('base64');

the component works fine on iOS :)

**Comment by fdambrosio** [comment]
thanks @matthieu80 & @glemiere

**Comment by glemiere** [comment]
You're welcome ;-)
