### ISSUE TITLE
clearing one specific image

### ISSUE THREAD

**Issue by matthieu80** [zyra/ionic-image-loader#106]
Hello there,
great plugin! I use it heavily on my app and it works great.
I just wonder how I could actually clear the cache for a specific image.
In my app, some pages shows images that have to be processed (resizing, cropping) to show correctly (around 10 seconds of process). If a user sees this page, the default fallback will show and stays forever until the user close and re-open the app.
Has anybody found a workaround for this kind of problem?

Thank you all!
Matt

**Comment by madoBaker** [comment]
Added feature in PR #192, wait for merge or just pull from branch if you need it right away

**Comment by madoBaker** [comment]
merged
