### ISSUE TITLE
Preloading images on app start up

### ISSUE THREAD

**Issue by EduardoBarrero** [zyra/ionic-image-loader#119]
Morgning guys!!

I'm facing with a behavior which I don't know if it is the correct one or I'm doing something wrong.
I need load some images on the app startup in order to use them lately in my app. In my app.component.ts I have the follow code:

```
platform.ready().then(() => {
imageLoader.preload(element.c_backgroundImage);
}
```

Lately in one of my pages i use these images:

`<img-loader src="{{item.c_backgroundImage}}" useImg="true" spinner="true"></img-loader>`

The problem is that when i call the preload method, it returns a promise to get the image from cache system. If the image is not in the cache system then it is downloaded from the internet, but this promise is executed when I use the image from the inner page, so the first time the image is going to be used (does not exists in cache) it takes some time in load the image. IT IS NOT A PRELOAD ACTUALLY :( What I need is that img is loaded (downloaded) from the internet on app startup always, so when I'm going to use lately the image is already downloaded.

Many thanks

**Comment by ihadeed** [comment]
You have to call the `.preload` function to preload images before they're used in a view.
