### ISSUE TITLE
Resolve preloading of multiple images

### ISSUE THREAD

**Issue by plindsay** [zyra/ionic-image-loader#120]
Thanks for this great library - I've found it very useful. One thing I thought might be great for my app would be to know when multiple images have been preloaded so I can then safely display the page content. 

I can see `imageLoader.preload()` returns a Promise but it only accepts a single image or asset URL. Could this also accept an array of URLs or is there a better approach to detecting when multiple images have been loaded and ready to display?

Cheers

**Comment by MikePaer** [comment]
Have you tried executing all your `imageLoader.preload()` calls in parallel, and awaiting the result of all of them, using `Promise.all()`?
```
let p1 = imageLoader.preload(...);
let p2 = imageLoader.preload(...);
let p3 = imageLoader.preload(...);

await Promise.all([p1, p2, p3]);
// at this point all images are preloaded and ready to display
```
Note: I haven't tested this.

**Comment by ihadeed** [comment]
The approach above should work.
