### ISSUE TITLE
cordova-plugin-file-transfer deprecation

### ISSUE THREAD

**Issue by westphalen** [zyra/ionic-image-loader#124]
Cordova Plugin FileTransfer has been deprecated since October, 2017.
Official suggestion is to use XHR2 (Angular's HttpClient).
https://cordova.apache.org/blog/2017/10/18/from-filetransfer-to-xhr2.html

Specifically, the deprecation is causing dependency errors in new projects, where latest versions of cordova-plugin-file and cordova-plugin-file-transfer are no longer compatible.

**Comment by allanpoppe** [comment]
I came here to open this issue.

**Comment by hi-rad** [comment]
Any news on this?
I want to start using this wonderful plugin but it keeps throwing file transfer dependency errors!

**Comment by allanpoppe** [comment]
@ihadeed can you post your modification to npm?

**Comment by ihadeed** [comment]
Done, published `ionic-image-loader@5.0.0`
