### ISSUE TITLE
How to build source code?

### ISSUE THREAD

**Issue by vhb56** [zyra/ionic-image-loader#126]
Hi, please help, wanted to use latest version, installed directly from github & error: can't find module.
I've looked inside folder - it must be compiled/build before, right? 
How i can do it, on win 10?

**Comment by ihadeed** [comment]
```
npm i
npm run build
```

**Comment by vhb56** [comment]
> How i can do it, on win 10?

` rm -rf aot dist && ngc
'rm' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by vhb56** [comment]
default win10 cli doesn't work with these commands.
git bash cli worked, but i had to re-clone repo, had some strange errors even with git bash cli.
anyway, thx for help.
