### ISSUE TITLE
images not loading on emulator

### ISSUE THREAD

**Issue by hi-rad** [zyra/ionic-image-loader#127]
Hi,

I have started using the latest version (5.0.0). It works perfectly in browser when using ionic serve, but when using ionic cordova emulate ios the images wont load and the spinner keeps spinning.

I am using this plugin in the following way:

`<img-loader src="/path/to/file" useImg></img-loader>`

**Comment by hi-rad** [comment]
@ihadeed Is this an issue or I did something wrong?

**Comment by ihadeed** [comment]
Not sure what `ion-image` is .. This module uses `img-loader`.

**Comment by hi-rad** [comment]
Sorry that was a mistake, i meant img-loader

**Comment by ihadeed** [comment]
Ok .. not sure at this point what the issue might be. I'll have to test it on an emulator when I get a chance. 

- Does it work fine on an actual iOS device?
- Does it work on Android emulators/devices?

**Comment by hi-rad** [comment]
I haven't tested it on a device and on an android device. I will test it and let you know ASAP.

**Comment by hi-rad** [comment]
@ihadeed I tested my app on an android device and it was working, but I haven't tried it on an actual iOS device

**Comment by lincolnthree** [comment]
Just to throw in a few of my observations if it helps. It seems this works fine in the browser, but on an actual Android device (Pixel 2XL) the images sometimes load but mostly just don't, and stay completely blank (I don't have a fallback image configured, fallback is disabled.)

**Comment by lincolnthree** [comment]
Reverting to 4.2.1 restores normal functionality.

**Comment by hi-rad** [comment]
@ihadeed have you looked into what @lincolnthree has mentioned?

**Comment by xProgrammer-007** [comment]
Android 6 still results with no image as explained by @lincolnthree  any clue or workarounds ? i tried base64 too , still no success.

**Comment by bhavincb** [comment]
+1 
with angular 5.0.0 not working. image loading fail with error 404. event url is correct and working

**Comment by ihadeed** [comment]
Should be fixed in the latest release, please re-open with steps to reproduce if you're still experiencing this issue.
