### ISSUE TITLE
CORS errors on Browser Platform

### ISSUE THREAD

**Issue by touficzayed** [zyra/ionic-image-loader#135]
Hi,

I use the plugin in android and ios, and it works pretty well.

My problem is on the browser platform. Strangely most of the images are not loaded with cors issue error messages in the console.

Do this plugin supports browser platform? What do I need to do to fix the cors error?

Thank you!

**Comment by ihadeed** [comment]
You need to fix/disable CORS on the server.
Also, try updating to latest version.
