### ISSUE TITLE
Version 5.0.0 not working on Android

### ISSUE THREAD

**Issue by paulstelzer** [zyra/ionic-image-loader#136]
I don't know why, but ionic-image-loader 5.0.0 is not working on Android. Switched back to 4.2.1 and there everything works as expected!

**Comment by Stfb** [comment]
I confirm it is not working with 5.0.0. Tried 4.2.1 and this is not working either on Android for me. But working on iOS.

**Comment by Stfb** [comment]
Ok so, It works with 5.0.0 with Android but you have to not use it in a browser or with live reload. I found that browsing through the code: check lines 81/82 image-loader.ts

**Comment by bhavincb** [comment]
hii @Stfb ,
can you please elaborate how did you configured it to work with 5.0.0? what do you mean by not use it in browser ? 
i am using command `ionic cordova run android`

**Comment by Stfb** [comment]
Hi @bhavincb ,

Si this is weird, I had problems making it working with android but after deleting the node_modules directory, it's working fine.

**Comment by bhavincb** [comment]
hii @Stfb ,
Thankx for quick response. i mine case removing platform and re-adding it solved the problem.
cordova-whitelist plugin was not added successfully which was causing the issue.

**Comment by Stfb** [comment]
Ah ok. Thanks for your feedback!
