### ISSUE TITLE
Reseting src no showing spinner

### ISSUE THREAD

**Issue by vasconcelosvcd** [zyra/ionic-image-loader#138]
Hi, I'm trying to set an src to an image after the components is loaded , but the spinner is now showing.

The case:
I'm uploading an image to a server, after that I get an link , then I set the link into the variable that is presenting on img-loader src and the spinner is not showing.

Ex:
HTML:
` <img-loader useImg [src]="imageUrl" ></img-loader>`

Component:

`this.api.sendImage(fd, null, "imageUpload").then((data: any) =>
                this.imageUrl = data.url;
            })`

After the link is received from the api the spinner is not showing while loading the image...

Thanks!

**Comment by fzamperin** [comment]
Hi @Vvasconcelos, have you tried interpolation in this case?? Instead of using [src] using src and then the interpolation like this:
`<img-loader useImg src="{{imageUrl}}" ></img-loader>`

**Comment by Vvasconcelos** [comment]
Hi @fzamperin, yes I've tried that... the workaround that I did was setting as the following:
` <img-loader useImg *ngIf="imageUrl" [src]="imageUrl" ></img-loader>`

then when I'm setting the value to empty or null, so every time the variable has an value it's destroy and remakes the component again, making the spinner work.

Thanks!

**Comment by ihadeed** [comment]
This should be fixed in the latest release.
