### ISSUE TITLE
Not load images on Angular 5.2.9 and Ionic 3.9.2

### ISSUE THREAD

**Issue by danieljulian9865** [zyra/ionic-image-loader#144]
Image not load and plugin no display any errors in console.

**Comment by bhavincb** [comment]
+1
same here

**Comment by bhavincb** [comment]
in network tab it shows error 404 but when i copy same url and open it in new tab. it works line charm

**Comment by bhavincb** [comment]
hi @danieljulian9865 ,
did you find any solution for this?

**Comment by Diegow3b** [comment]
+1

**Comment by pjc0247** [comment]
+1

**Comment by DimitriGuitton** [comment]
Did you find a solution ?

**Comment by Diegow3b** [comment]
Guy search for Dom Sanitizer, that solve my problem

**Comment by danielsogl** [comment]
I can not reproduce this error without further informations.

**Comment by Sudhir22sep** [comment]
@jimmywong185 how come you got with the updated one. i am unable to get the image in cache.

**Comment by ihadeed** [comment]
Should be fixed in the latest release.
