### ISSUE TITLE
Can't install without having any child child/shared module(s) and only having app.module.ts.

### ISSUE THREAD

**Issue by Fieel** [zyra/ionic-image-loader#147]
Hello.

I have a Ionic project but i can't even get this plugin installed. I'm not using child/shared modules, i have only app.module.ts and not single <pageName>.module.ts like the installation steps implies, this is the step i'm talking about:

**Then add `IonicImageLoader` in your child/shared module(s)**
```
import { IonicImageLoader } from 'ionic-image-loader';
 
@NgModule({
  ...
  imports: [
    IonicImageLoader
  ]
})
export class SharedModule {}
```

How am i supposed to install this

**Comment by nncl** [comment]
@Fieel, in this case, it'd be your page's module.

**Comment by Fieel** [comment]
@nncl I don't have page's modules.
