### ISSUE TITLE
Doesn't work with Ionic Webview 1.2

### ISSUE THREAD

**Issue by ahmadtawakol** [zyra/ionic-image-loader#148]
Images fail to load using Ionic Webview 1.2. Downgrading to 1.1.9 works fine.

The error in the console says it failed to load the image, resource not found.

**Comment by mahnuh** [comment]
I can confirm that, spent 2 hours wondering why it suddenly stopped working. Downgrading to 1.1.9 helps.

**Comment by sabiridwan** [comment]
hi!! @mahnuh  @ahmadtawakol  i downgrade to "cordova-plugin-ionic-webview": "^1.1.9" and is still not working. IOS 11.3.

**Comment by mahnuh** [comment]
Did you verify which version actually is installed? Go to plugins/cordova-plugin-ionic-webview/package.json to do so. If 1.2.0 is installed do

ionic cordova plugin remove cordova-plugin-ionic-webview && ionic cordova plugin add cordova-plugin-ionic-webview@1.1.19

This will install 1.1.19. You should also remove the ^ from the version in your project’s package.json.

**Comment by mtshare** [comment]
Same for me!

**Comment by allanpoppe** [comment]
Same here.

**Comment by SnehaSSD** [comment]
Same for me. Any solution for it ?

**Comment by AbuHani** [comment]
I have same issue, i tried to downgrade as mentioned and it didn't solve it.

I looked for this PR [137](https://github.com/zyra/ionic-image-loader/pull/137) that fix the issue with CORS requests and tried it on  emulator but the images not displaying properly.

Has anyone get the solution?

**Comment by mahnuh** [comment]
Ionic webview 1.2.1 is working for me.

**Comment by eduardoRoth** [comment]
Created pull request #160 to fix this, instead of replacing the `file:///` with `http://localhost:8080/` I used Ionic own function `normalizeUrl` and it's working now in iOS with WKWebView.

**Comment by ihadeed** [comment]
@eduardoRoth merged!
