### ISSUE TITLE
Same image downloaded multiples times

### ISSUE THREAD

**Issue by Stiveknx** [zyra/ionic-image-loader#149]
See this example:

.ts
```
let images = ['https://mydomain/img1.jpg',
                     'https://mydomain/img2.jpg',
                     'https://mydomain/img3.jpg',
                     'https://mydomain/img1.jpg']
```

theme.html
```
<ion-item *ngFor="let img of images">
        <ion-avatar item-start>
                <img-loader useImg="true" src="{{img}}"></img-loader>
       </ion-avatar>
</ion-item>
```

The img1.jpg, is exatcly the same picture, sure
Well, I'm seeing it getting downloaded multiple times, and generating multiple caches, for the same image - same file. Is there any way to avoid it? And download only once ... 

Thanks.

**Comment by jonasschumacher** [comment]
Have you tried it again? I guess it was resolved in #163.
