### ISSUE TITLE
Property 'preload' does not exist on type 'ImgLoader'.

### ISSUE THREAD

**Issue by Sawannrl123** [zyra/ionic-image-loader#154]
It giving me error. I am using like this

import { ImgLoader } from 'ionic-image-loader';
constructor(imageLoader: ImgLoader) {
     imageLoader.preload('http://path.to/image.jpg'); //GIves error - Property 'preload' does not exist on type 'ImgLoader'.
}

I am following this https://github.com/zyra/ionic-image-loader#global-configuration

**Comment by zajcman** [comment]
I have the same problem when i want use ..setConcurrency .  Property does not exist. And i don't know why i don't see spinner but i have this code : 
 <img-loader src="{{news.img_url[0]}}" useImg spinner="true"></img-loader>

**Comment by ihadeed** [comment]
Make sure you're using the latest version
