### ISSUE TITLE
Won't work with ionic 4: Cannot find module 'ionic-angular'

### ISSUE THREAD

**Issue by matheusdavidson** [zyra/ionic-image-loader#159]
The plugin breaks with ionic 4, ```ionic-angular``` became ```@ionic/angular```.

Error when i try to use it:
```bash
[ng] ERROR in ./node_modules/ionic-image-loader/dist/image-loader.module.js
[ng] Module not found: Error: Can't resolve 'ionic-angular' in '/private/var/www/youchange/hibrido/node_modules/ionic-image-loader/dist'
[ng] ERROR in ./node_modules/ionic-image-loader/dist/providers/image-loader.js
[ng] Module not found: Error: Can't resolve 'ionic-angular' in '/private/var/www/youchange/hibrido/node_modules/ionic-image-loader/dist/providers'
[ng] ERROR in ./node_modules/ionic-image-loader/dist/providers/image-loader.js
[ng] Module not found: Error: Can't resolve 'rxjs/Observable' in '/private/var/www/youchange/hibrido/node_modules/ionic-image-loader/dist/providers'
[ng] ERROR in ./node_modules/ionic-image-loader/dist/providers/image-loader.js
[ng] Module not found: Error: Can't resolve 'rxjs/add/operator/first' in '/private/var/www/youchange/hibrido/node_modules/ionic-image-loader/dist/providers'
[ng] ℹ ｢wdm｣: Failed to compile.
[ng]
[ng] ERROR in node_modules/ionic-image-loader/dist/providers/image-loader.d.ts(4,26): error TS2307: Cannot find module 'ionic-angular'.
```

**Comment by matheusdavidson** [comment]
Also, there is a problem with rxjs, it happens because ionic 4 uses angular 6 with rxjs 6. There are some breaking changes in rxjs 6, a workaround for now is to install rxjs-compat: ```npm install --save rxjs-compat``` which solves the problem with rxjs.

**Comment by danielsogl** [comment]
I will update the plugin to Angular 6 after the official Ionic 4 release. Until now you can use the [rxjs-compat package](https://www.npmjs.com/package/rxjs-compat) to solve the rxjs build errors.

**Comment by matheusdavidson** [comment]
ionic 4 beta is out

**Comment by danielsogl** [comment]
I will start next week with the @next releases for all of your open source projects.

**Comment by krishnakanthTM** [comment]
Is this issue solved ? now am getting `Cannot find module '@ionic/angular'.`
`...ectable/src/app/components/ionic-selectable/ionic-selectable-page.component.d.ts`

**Comment by nextbyn** [comment]
> Is this issue solved ? now am getting `Cannot find module '@ionic/angular'.`
> `...ectable/src/app/components/ionic-selectable/ionic-selectable-page.component.d.ts`
> `import { Content, InfiniteScroll, NavParams } from '@ionic/angular';`

Same error here.

**Comment by madoBaker** [comment]
Sorry guys, closed it on accident, my fault. However, you can track the latest work under the `v4` branch. Soon come!

**Comment by aravind14feb** [comment]
Thanks to the contributors for this useful library. It would be helpful for me to know when would the v4 branch works be completed and merged into master.

**Comment by aravind14feb** [comment]
@ihadeed  Thank you very much.

**Comment by aravind14feb** [comment]
@ihadeed  I tried to use the beta version. I'm getting this error while loading the image

`ImageComponent.html:3 ERROR Error: StaticInjectorError(AppModule)[ImageLoaderService -> WebView]: 
  StaticInjectorError(Platform: core)[ImageLoaderService -> WebView]: 
    NullInjectorError: No provider for WebView!
    at NullInjector.push../node_modules/@angular/core/fesm5/core.js.NullInjector.get (core.js:1062)
    at resolveToken (core.js:1300)
    at tryResolveToken (core.js:1244)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (core.js:1141)
    at resolveToken (core.js:1300)
    at tryResolveToken (core.js:1244)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (core.js:1141)
    at resolveNgModuleDep (core.js:8369)
    at _createClass (core.js:8422)
    at _createProviderInstance (core.js:8386)
View_ImageComponent_0 @ ImageComponent.html:3`

Can someone point me in the right direction?

And I see that the library requires few ionic native plugins..  I wanted to know whether I can use this library for the PWA, which would require to run on a desktop Browser.

**Comment by aravind14feb** [comment]
> @ihadeed I tried to use the beta version. I'm getting this error while loading the image
> 
> `ImageComponent.html:3 ERROR Error: StaticInjectorError(AppModule)[ImageLoaderService -> WebView]: StaticInjectorError(Platform: core)[ImageLoaderService -> WebView]: NullInjectorError: No provider for WebView! at NullInjector.push../node_modules/@angular/core/fesm5/core.js.NullInjector.get (core.js:1062) at resolveToken (core.js:1300) at tryResolveToken (core.js:1244) at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (core.js:1141) at resolveToken (core.js:1300) at tryResolveToken (core.js:1244) at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (core.js:1141) at resolveNgModuleDep (core.js:8369) at _createClass (core.js:8422) at _createProviderInstance (core.js:8386) View_ImageComponent_0 @ ImageComponent.html:3`
> 
> Can someone point me in the right direction?
> 
> And I see that the library requires few ionic native plugins.. I wanted to know whether I can use this library for the PWA, which would require to run on a desktop Browser.

My mistake about the error. Missed importing the WebView in the module.

**Comment by v4varin** [comment]
Try 
import { NavController } from '@ionic/angular'; 

instead of 
import { NavController } from 'ionic-angular'

**Comment by heshaShawky** [comment]
Still not working guys with ionic v4.0.0.rc1

I have tried every solution possible like installing rxjs-compat, install image loader beta, editing my tsconfig to allowjs ..etc  and non working 

This the error I got: 
 
[ng] ERROR in node_modules/ionic-image-loader/lib/services/image-loader.service.d.ts(2,22): error TS2307: Cannot find module '@ionic-native/file/ngx'.
[ng] node_modules/ionic-image-loader/lib/services/image-loader.service.d.ts(3,25): error TS2307: Cannot find module '@ionic-native/ionic-webview/ngx'.
[ng]
[ng]
[ng] Date: 2019-01-19T15:25:51.982Z - Hash: 241df9a347e148fb5b00 - Time: 5084ms
[ng] 179 unchanged chunks
[ng] chunk {directory-directory-module} directory-directory-module.js, directory-directory-module.js.map (directory-directory-module) 62.5 kB  [rendered]
[ng] chunk {main} main.js, main.js.map (main) 35.8 kB [initial] [rendered]
[ng] chunk {vendor} vendor.js, vendor.js.map (vendor) 5.25 MB [initial] [rendered]
[ng]
[ng] ERROR in ./node_modules/ionic-image-loader/fesm5/ionic-image-loader.js
[ng] Module not found: Error: Can't resolve '@ionic-native/file/ngx' in 'D:\Projects\dalal-complex-final\node_modules\ionic-image-loader\fesm5'
[ng] ERROR in ./node_modules/ionic-image-loader/fesm5/ionic-image-loader.js
[ng] Module not found: Error: Can't resolve '@ionic-native/file/ngx/index' in 'D:\Projects\dalal-complex-final\node_modules\ionic-image-loader\fesm5'
[ng] ERROR in ./node_modules/ionic-image-loader/fesm5/ionic-image-loader.js
[ng] Module not found: Error: Can't resolve '@ionic-native/ionic-webview/ngx' in 'D:\Projects\dalal-complex-final\node_modules\ionic-image-loader\fesm5'
[ng] ERROR in ./node_modules/ionic-image-loader/fesm5/ionic-image-loader.js
[ng] Module not found: Error: Can't resolve '@ionic-native/ionic-webview/ngx/index' in 'D:\Projects\dalal-complex-final\node_modules\ionic-image-loader\fesm5'

**Comment by aayushikh02** [comment]
install this first '  npm i @ionic/angular ' and then replace ionic-angular with @ionic/angular

**Comment by alanany** [comment]
thanks 
Allah gift you paradise

**Comment by ebeliejinfren** [comment]
> install this first ' npm i @ionic/angular ' and then replace ionic-angular with @ionic/angular

i install ionic/angular but it's not work and got error, also imports are 
`import { IonicModule, IonicRouteStrategy } from '@ionic/angular';`

**Comment by alanany** [comment]
thanks
problem solved
but i want to know how to publish ionic 3 to apk

**Comment by OAnouman** [comment]
Hello guys! I still got the same issue. @alanany how did you solve it ?

**Comment by TheMasterSloth** [comment]
Tried it today it still gives the same error.

**Comment by ebeliejinfren** [comment]
### i think this plugin not update

**Comment by OAnouman** [comment]
Yeah, this plugin needs some updates...

**Comment by Ademking** [comment]
did anyond found a solution ?

**Comment by LyonOconner** [comment]
Solution ??

**Comment by LyonOconner** [comment]
npm i ionic-angular

import {ViewController , IonicPage, NavController, Platform } from 'ionic-angular';

**Comment by ihadeed** [comment]
It's amazing how [my comment](https://github.com/zyra/ionic-image-loader/issues/159#issuecomment-449566453) just went unnoticed. 

The beta version of this plugin that is designed for Ionic 4 is ready, and published to NPM. 

Closing this issue since it's clearly misleading and not helpful.
