### ISSUE TITLE
Feature Request: Ability to Apply Directives

### ISSUE THREAD

**Issue by tabirkeland** [zyra/ionic-image-loader#17]
First off, thank you for this package, it is great.

It would be great to have the ability to apply other directives to the component and have them then applied to the `<img/>` element.  For example I am also using [this](https://github.com/Riron/ionic-img-viewer) package in my project.  In order to apply it to an image element the markup would look something like:

```html
<img-loader [src]="map" useImg [spinner]="false" imageViewer></img-loader>
```

**Comment by ihadeed** [comment]
Sure we can add this. I'm not sure how to do it but I'll do my research. 

If you find any library that offers this kind of functionality, let me know and I'll have a look at how it's done. 

I can read the attributes on `img-loader` and add them to the `img` element ([here](https://github.com/zyramedia/ionic-image-loader/blob/master/src/components/img-loader/img-loader.ts#L141)). But I'm not sure if it will register as a directive. I will need to test this out.

**Comment by tabirkeland** [comment]
Right, I was thinking something of something along those lines.  Get the native element (attribute/values)[http://stackoverflow.com/questions/2048720/get-all-attributes-from-a-html-element-with-javascript-jquery], iterate and attach to the `img` element,.  I'm not sure if they would register either.  I'll try and test when I have time as well.  Thanks.

**Comment by ihadeed** [comment]
I just tested it out, it doesn't work. I'm able to apply the attributes to the child element, but Angular doesn't use them as a directive. I think the directive needs to be defined in compile time. 

Another idea I have is to create a directive for `ionic-image-loader` that you can attach to an `img` tag. To make this work, you can no longer use the `src` tag to define the image URL. AFAIK that's the only way to stop the browser from loading the image automatically. This will allow the directive to cache the image and then set the `src` tag. The `imageViewer` directive tries to access the `src` value only when a `click` event has fired (see [here](https://github.com/Riron/ionic-img-viewer/blob/master/src/image-viewer.directive.ts#L20)). This means that if the user clicks on the image before it's loaded, it will break the `ImageViewer` component.

**Comment by tabirkeland** [comment]
That makes sense.  Once `src` is set, the image starts to download.  Would doing some kind of async pre-loading be possible?

```typescript
let img = new Image();
img.addEventListener('load', () => {
  //
});
img.src = 'image.png';
```
From there, `img` there is now a [HTMLIMageElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/Image).  Then you could attach any other element attributes (i.e. directives) to it and place it on the DOM?

**Comment by ihadeed** [comment]
> I'm able to apply the attributes to the child element, but Angular doesn't use them as a directive. I think the directive needs to be defined in compile time.

Attaching an attribute dynamically won't register as a directive. 

The following is possible but I need to test it to make sure it works:

HTML code will look as follows:
```html
<img [imageSrc]="https://path/to/image.png" imageLoader imageViewer />
```

Then in the TypeScript code, I can host the `click` event and call `stopPropagation`  if the image is not loaded yet. This should stop any click event handlers from functioning. I'm just not sure if it has any effect on the `imageViewer` event handler, or if it would run before the `imageViewer` handler runs.

**Comment by ihadeed** [comment]
I was just looking at the Ionic Img Viewer module, looks like you can now use it with this module without any issues.

```
<img-loader [src]="imagePath" [imageViewer]="imagePath"></img-loader> 
```

**Comment by tabirkeland** [comment]
@ihadeed thank you!
