### ISSUE TITLE
Ionic File Transfer Plugin Deprecation

### ISSUE THREAD

**Issue by ahmadlinus** [zyra/ionic-image-loader#170]
Hi, 

as Ionic File Transfer Plugin is going to be deprecated, I wanted to remind the maintainers of this repository to change your codebase to something which will be supported by the ionic Cordova community. 

Thanks a lot

**Comment by felixbroehl** [comment]
Thanks for your notice. ionic-image-loader is not using the file transfer plugin since version 5.0.0. This could be closed.

**Comment by ahmadlinus** [comment]
Thanks for the information. We should update our project then.
