### ISSUE TITLE
Fallback fail when load multiple same image source

### ISSUE THREAD

**Issue by l1nknyto** [zyra/ionic-image-loader#174]
Hi Zyra,

When using img-loader to load **same image source at the same time**, only one fallback image is loaded, others are still showing spinner.
This happened in Android (not test in iOS yet). I got HttpErrorResponse when i am enable debug mode. Any HttpErrorResponse.status = 0 or 404, give the same behaviour as i described above.

```
    <img-loader src="https://path.to/not-found.jpg" fallback="./assets/imgs/no-image.png"></img-loader>
    <img-loader src="https://path.to/not-found.jpg" fallback="./assets/imgs/no-image.png"></img-loader>
    <img-loader src="https://path.to/not-found.jpg" fallback="./assets/imgs/no-image.png"></img-loader>
```

Thanks for your help

**Comment by jonasschumacher** [comment]
I'm almost sure that #176 fixes this issue.

**Comment by l1nknyto** [comment]
@jonasschumacher yes, you right.
i already test with your git fork and it did fix the issue.

Thank you.

**Comment by ihadeed** [comment]
This is fixed in the latest release
