### ISSUE TITLE
Fatal: crashes on ios

### ISSUE THREAD

**Issue by stephan-strate** [zyra/ionic-image-loader#181]
After updating **ionic-team/cordova-plugin-ionic-webview** to version 2.0.2 the app
is crashing at start.

When we remove the ionic-image-loader from our app, it does not crash.

Also it does not crash, when we load the app, while we do not have internet connection.

We are on ionic-image-loader version: 5.0.5

ionic info
```
Ionic:

   ionic (Ionic CLI)  : 4.0.1
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.9

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0, ios 4.5.4

System:

   NodeJS : v8.9.4 (C:\Program Files\nodejs\node.exe)
   npm    : 5.6.0
   OS     : Windows 10
```

**Comment by Ross-Rawlins** [comment]
Did you resolve this issue?

**Comment by stephan-strate** [comment]
> Did you resolve this issue?

Unfortunately no, do you have a solution?
We need to fix this issue as fast as possible to publish our app.

**Comment by Ross-Rawlins** [comment]
I rolled back my webview version to an older version.

**Comment by Dema1348** [comment]
I have the same issue 😢 , app crash when is loading the image

**Comment by stephan-strate** [comment]
> I have the same issue 😢 , app crash when is loading the image

We managed to fix the issue with the suggested solution in #183.

**Comment by Dema1348** [comment]
I found another solution, update the plugin  cordova-plugin-ionic-webview to latest and now is working
