### ISSUE TITLE
Can install - See error

### ISSUE THREAD

**Issue by bharned3** [zyra/ionic-image-loader#188]
Not sure how to fix this. can anyone help me understand whats missing: 

sudo npm install --save ionic-image-loader
npm WARN @ionic-native/file@4.12.2 requires a peer of @ionic-native/core@^4.11.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/file@4.12.2 requires a peer of rxjs@^5.5.11 but none is installed. You must install peer dependencies yourself.

**Comment by ihadeed** [comment]
- What version of `@ionic-native/core` do you have installed?
- What version of `rxjs` do you have installed?

**Comment by bharned3** [comment]
I have "@ionic-native/core": "^4.4.0" and rxjs": "5.5.2" I will try updating thanks
