### ISSUE TITLE
is image download completed

### ISSUE THREAD

**Issue by abdellahaski** [zyra/ionic-image-loader#195]
is there a way to know when the image load has completed ?
I've tried this: 
(load)="onImageLoad($event)
but it's fired before the image download has completed so it's not what I'm looking for

**Comment by madoBaker** [comment]
should be fixed with latest PR

**Comment by abdellahaski** [comment]
Thanks so much, but can I know how I can apply those changes to my ionic project,
should I just edit  src/components/img-loader.ts on the plugin directory on my node_modules? or I need to kinda build the module to get an updated dist directory ? 
I'm sorry I new here so..

**Comment by madoBaker** [comment]
`npm i -S ionic-image-loader@latest` should do it

**Comment by madoBaker** [comment]
just a side note, unless you're trying to get a hacky fix to a certain module, you never want to edit anything inside the `node_modules` dir

**Comment by abdellahaski** [comment]
Oh thanks man I didn't thought it's updated to npm 
Thanks for the advice
