### ISSUE TITLE
image not showing when I build for android

### ISSUE THREAD

**Issue by abdellahaski** [zyra/ionic-image-loader#197]
I have a problem Images are not showing on android it's failling back to the fall back image that I've set, it only happen when I built the apk file
it was working fine when I was debugging using my browser or the same phone (that I've tested the apk on)  either via the "ionic serve -c" and using the ionic dev app or by running this command : "ionic cordova run android -l -c -s --debug" both worked well and I was able to see the images 
but when I built the apk file using ionic cordova run/build all images fail back to the fallback image.

I've tried signing the apk it didn't help

One more thing I don't know if it related on android it doesnt ask for storage permission I don't know if it should or not.

here is my versions: 
```
"ionic-angular": "3.9.2",
"cordova-plugin-file": "^6.0.1",
"@ionic-native/file": "^4.14.0",
"ionic-image-loader": "6.3.0",
```

and here is my config: 
```
this.imageLoaderConfig.enableSpinner(true);
this.imageLoaderConfig.useImageTag(true);
this.imageLoaderConfig.setFallbackUrl('assets/imgs/fallbackimg.jpg');
this.imageLoaderConfig.setMaximumCacheAge(7 * 24 * 60 * 60 * 1000);
this.imageLoaderConfig.setImageReturnType('base64');
```
My phone's android version is 8.1.0 (MIUI 10.0.1.0)

Thanks

**Comment by madoBaker** [comment]
Does anything show up in the console logs?

**Comment by oxxginoxxo** [comment]
I have the same problem on android

**Comment by abdellahaski** [comment]
Thanks @madoBaker for pointing out the logs.
Since I didn't have this problem while running via my PC and it was only happening with the "<img-loader" tag "<img >" was working as usual, I thought it's an Image Loader bug,
I've checked the logs via an android logcat viewer and I found this:

`"Failed to load http://****/20180920/0615.jpg: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.", source: http://localhost:8080/ (0)`

Yeah it was only a CORS issue where my images resides, so it can easily be solved by adding these lines to the .htaccess if you're running apache and you're hosting the images on it  :
```
<IfModule mod_headers.c>
Header set Access-Control-Allow-Origin "*"
</IfModule>
```
