### ISSUE TITLE
imgAttributes failing

### ISSUE THREAD

**Issue by jfbourne** [zyra/ionic-image-loader#202]
`core.js:1633 ERROR Error: Uncaught (in promise): TypeError: this.imgAttributes.forEach is not a function
TypeError: this.imgAttributes.forEach is not a function`

implementation: 

` <img-loader fallbackUrl="defaultImg" [src]="photo.url" imgAttributes="imageAttributes" useImg="true"></img-loader>`

**Comment by eduardoRoth** [comment]
It should be:

```
<img-loader [fallbackUrl]="defaultImg" [src]="photo.url" [imgAttributes]="imageAttributes" useImg="true"></img-loader>
```

If `defaultImg` and `imageAttributes` are variables.

**Comment by jfbourne** [comment]
Thanks, rookie mistake.
