### ISSUE TITLE
cache not working on both iOS and Android devices

### ISSUE THREAD

**Issue by xinfengmich** [zyra/ionic-image-loader#203]
I tried to use Ionic Image loader to load google street view images in order to reduce the requests to Google.  I set cache time to 30 days as
imageLoaderConfig.setMaximumCacheAge(30 * 24 * 60 * 60 * 1000); 

After more that one day ( since google street view images HTTP caching 1 day by default ), turned on 'Airplane Mode' on both Android and iOS devices,  then tried to view the image that I viewed before.  The image wasn't loading, looked like still sending the http request to Google and not loading the image from local cache.  

Any help would be appreciated.

**Comment by xinfengmich** [comment]
Use  "ionic-image-loader": "6.3.0",  "@ionic-native/file": "4.13.0",  "cordova-plugin-file": "6.0.1",

**Comment by Ross-Rawlins** [comment]
I followed your steps and its still failing for me it says it cant access the path. When I look at the path it has both localhost and file:// in it.

**Comment by xinfengmich** [comment]
On iOS, it looked like  
background-image: url(http://localhost:8080/var/mobile/Containers/Data/Application/0ADF9302-E587-403A-91F0-1AE57FBE6658/Library/Caches/image-loader-cache/2023760148); background-repeat: no-repeat no-repeat;">
On Android, it looked like
background-image: url(&quot;file:///data/user/0/edu.umich.mobile.MichTDev/cache/image-loader-cache/1420132908&quot;);

I'm upgrading  "ionic-image-loader" to the latest version 6.3.2 and see if it will fix my problem.

**Comment by Ross-Rawlins** [comment]
So after further investigation the working app gets a path of 
file:///data/user/0/myApp/cache/image-loader-cache/1046963097

but the broken app returns a path like this http://localhost:8080/_file_/data/user/0/bundleID/cache/image-loader-cache/1088978943

**Comment by Ross-Rawlins** [comment]
Looks to be a webview issue.

**Comment by tnovau** [comment]
Yes, I'm facing the same issue here. Please let me know if you can solve it

**Comment by rubennavarroc** [comment]
Hello, with the newest ionic webview it should give you a transformed url, which is wrong anyway because of a webview bug. Try using base64 image instead.

**Comment by Ross-Rawlins** [comment]
@rubennavarroc the webview guys are saying there is no reported issue with them.

**Comment by tnovau** [comment]
Thanks @rubennavarroc I changed to base64 and it's working smooth.

**Comment by xinfengmich** [comment]
"ionic-image-loader"  version 6.3.2 worked for me.

**Comment by pcsantana** [comment]
@Ross-Rawlins did you get it to work?

I'm facing the same problem after update to ionic webview 2.x.
I saw the workaround to convert to base64, but if possible I would like to use file uri.

**Comment by xinfengmich** [comment]
I have the same issue when updating to ionic webview 2.x. 
See https://github.com/zyra/ionic-image-loader/issues/206
I get google street view images which no file extension in the URL,  with "cordova-plugin-ionic-webview": "2.3.1", it can't load on Android device.
