### ISSUE TITLE
img-loader not working inside ion-avatar

### ISSUE THREAD

**Issue by nylz** [zyra/ionic-image-loader#234]
**Using:**
"ionic": "^4.8.0",
"ionic-image-loader": "^7.0.0-beta.2",
"@ionic/angular": "4.0.0-beta.17",

**Problem:**
It's not working inside <ion-avatar ...> for me.
Example:
`    <ion-item>
      <ion-avatar slot="start">
        <img-loader [src]="getUserAvatarUrl(object.ownerid)" ></img-loader>
      </ion-avatar>
      <ion-label>...      </ion-label>
    </ion-item>
`
the image is shown as if the ion-avatar wasn't surrounding it. Its the plain image - no rounded corners.

Configuration in app.component.ts is:
this.imageLoaderConfig.useImageTag(true);

Can s.o. please fix this or tell me a workaround?
thanks in advance

**Comment by lincolnthree** [comment]
I don't know anything about this issue, but I'd suggest looking at the CSS to figure out what's going on. You can always style the image yourself with a bit of custom CSS in your page.

**Comment by vkyeswa** [comment]
@nylz give it height, say 50px if you have not used the useImg attribute. I think ion-avatar looks out for <img> tag

**Comment by nylz** [comment]
It IS in useIMG-Mode. But You're probably right, when You say, that there fails a search for an img-tag. So I helped myself by doing the following:

`
      <ion-avatar slot="start">

        <img-loader [src]="getUserAvatarUrl(object.ownerid)" (click)="show_detail(object, i)"
          [imgAttributes]="[{'element': 'class', 'value': 'round-avatar avatar-48'}]"></img-loader>

      </ion-avatar>
`
and in CSS, I added:
`.round-avatar {
  border-radius: 20px;
}
`
this solution works so far. A workaround, but it's ok.
