### ISSUE TITLE
Uncaught Error: Can't resolve all parameters for ImageLoader: ([object Object], ?, [object Object], [object Object])

### ISSUE THREAD

**Issue by herquiloidehele** [zyra/ionic-image-loader#235]
I installed this package on my ionic 3 app and folowed all installation steps, but when i serve my project it shows this error

**Comment by AmineMediazain** [comment]
can someone answer this question please !!?

**Comment by jlcasasg** [comment]
Hi! I was facing the same issue.
I fixed using 
`npm add --save @ionic-native/file@^4.0.0`

**Comment by herquiloidehele** [comment]
thanks @jlcasasg .

**Comment by burakodabas** [comment]
thanks @jlcasasg

**Comment by L96Github** [comment]
Also happens when you have a version of `ionic-native` higher than `^4.0.0`

**Comment by byronglendon** [comment]
Any solutions for Angular6/7 requiring @ionic/native/: "^5.1.0",

**Comment by abePdIta** [comment]
npm i -S ionic-image-loader@beta
npm i -S @ionic-native/ionic-webview
Do not forget to `import { WebView } from '@ionic-native/ionic-webview/ngx';` and add `WebView` to provider list in your app module.

**Comment by kkduniya** [comment]
update all file ionic-image-loader file with file/ngx from like 'import { File, FileEntry }  from '@ionic-native/file/ngx';
