### ISSUE TITLE
@ionic-native/file": "^5.1.0 compatibility

### ISSUE THREAD

**Issue by peterpullmann** [zyra/ionic-image-loader#239]
Hi,
please this plugin is fantastic for image loading. But due the other requirements I need to update to @ionic-native/file": "^5.1.0 and this plugin require file@4.x version.

Please do you plan to upgrade, or anyone else do you please know how to fix it?

Thanks a lot.
Peter

**Comment by peterpullmann** [comment]
I found v4 branch, but it is not compatible with ionic 5.1.0.

**Comment by ihadeed** [comment]
@peterpullmann how is it not compatible?

If it's just throwing a warning when doing `npm i` that you have unmet peer dependencies, you can ignore it and keep using latest version of `@ionic-native/file`.

Otherwise, please provide more details about any errors or issues you're experiencing.

**Comment by L96Github** [comment]
Same issue. Have dependencies that do not allow me to have lower than `ionic-native: 5.0.0`.

Its an amazing plugin, are there any plans to update it?

Besides the warning it also **doesn't work**.
Gives an error.
`Uncaught Error: Can't resolve all parameters for ImageLoader: ([object Object], ?, [object Object], [object Object]`

thats with `ionic-native: 5.6.0
`
