### ISSUE TITLE
Ionic 4 not working (using beta version of ionic-image-loader)

### ISSUE THREAD

**Issue by Ademking** [zyra/ionic-image-loader#242]
Can someone help me using ionic-image-loader with Ionic 4 ?
i installed the beta version (v4) of ionic-image-loader.
i got this error 

**ERROR in node_modules/ionic-image-loader/lib/services/image-loader.service.d.ts(3,25): error TS2307: Cannot find module '@ionic-native/ionic-webview/ngx'.
[ng]**

How to fix that ?

Thanks

**Comment by ihadeed** [comment]
You need to run `npm i -S @ionic-native/ionic-webview`

**Comment by 2diegoduque** [comment]
To date it still does not work in ionic 4, in console the following errors come out after doing

`npm i -S @ionic-native/ionic-webview`

>  ERROR in ./node_modules/ionic-image-loader/dist/image-loader.module.js 
Module not found: Error: Can't resolve 'ionic-angular' in 'C:\wamp64\www\folder\node_modules\ionic-image-loader\dist'

> ERROR in ./node_modules/ionic-image-loader/dist/providers/image-loader.js 
Module not found: Error: Can't resolve 'ionic-angular' in C:\wamp64\www\folder\node_modules\ionic-image-loader\dist\providers'

> ERROR in ./node_modules/ionic-image-loader/dist/providers/image-loader.js
Module not found: Error: Can't resolve 'rxjs/observable/fromEvent' in  'C:\wamp64\www\folder\node_modules\ionic-image-loader\dist\providers'

**Comment by robertnicjoo** [comment]
`ionic-angular` has changed to `@ionic/angular` in version 4 but this package still use old version, any help?

I tried to edit files myself but it didn't work and also another issue was if this packages gets update all my edits would be re-write.

Ideas?

**Comment by shermansmithh** [comment]
> `ionic-angular` has changed to `@ionic/angular` in version 4 but this package still use old version, any help?
> 
> I tried to edit files myself but it didn't work and also another issue was if this packages gets update all my edits would be re-write.
> 
> Ideas?

Did you find the solution?

**Comment by Fieel** [comment]
> > `ionic-angular` has changed to `@ionic/angular` in version 4 but this package still use old version, any help?
> > I tried to edit files myself but it didn't work and also another issue was if this packages gets update all my edits would be re-write.
> > Ideas?
> 
> Did you find the solution?

I found one which worked for me here https://github.com/zyra/ionic-image-loader/issues/209#issuecomment-525661515
