### ISSUE TITLE
No provider for WebView! with @ionic-native/ionic-webview 5.3.0

### ISSUE THREAD

**Issue by Mazus** [zyra/ionic-image-loader#244]
Hello,

After updating to latest angular and ionic versions (angular 7.2.11 , ionic 4.1.1 )
@ionic-native/ionic-webview 5.3.0

I have this issue when using <img-loader>:

 Error: StaticInjectorError(AppModule)[ImageLoaderService -> WebView]: 
  StaticInjectorError(Platform: core)[ImageLoaderService -> WebView]: 
    NullInjectorError: No provider for WebView!
    at NullInjector.push../node_modules/@angular/core/fesm5/core.js.NullInjector.get (core.js:8896)
    at resolveToken (core.js:9141)
    at tryResolveToken (core.js:9085)

Going back to @ionic-native/ionic-webview 5.2.0 solved the issue.

I'm using ionic-image-loader 7.00-beta.2.

Thanks

**Comment by SebastienBtr** [comment]
I your app module you need to add : import { WebView } from '@ionic-native/ionic-webview/ngx';
and in the provider list to add : WebView

I'm using ionic-image-loader 7.00-beta.2. and @ionic-native/ionic-webview 5.3.0

**Comment by Mazus** [comment]
@SebastienBtr  Thanks a lot, that did work.
Is this a broader problem related to ionic-webview 5.3.0 or this only concerns ionic-image-loader ?
