### ISSUE TITLE
Can we see sources for beta versions?

### ISSUE THREAD

**Issue by gartorware** [zyra/ionic-image-loader#255]
Hello there,

I'm trying to use this library with ionic 4. I have installed beta versions (7.0.0-beta.2) but it still have some flaws. I then decided to solve them, but I cannot find source code for this version, neither in branches nor in tags. So I wonder... Is this code available somewhere? Is the v4 branch the way to go? (I can see  differences between v4 commits and beta.2 publish date)

Regards.

**Comment by ihadeed** [comment]
@gartorware the source is in the v4 branch: https://github.com/zyra/ionic-image-loader/tree/v4

Named it v4 as in it's for Ionic 4, but that's the 7.0.0-beta.x branch
