### ISSUE TITLE
ionic native 3 with last version image loader

### ISSUE THREAD

**Issue by MarinoRaul** [zyra/ionic-image-loader#31]
I got this error when i try run this plugin ...

bundle failed: 'FileReader' is not exported by node_modules/@ionic-native/file/index.js (imported 
by node_modules/ionic-image-loader/dist/providers/image-loader.js). For help fixing this 
error see https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module 

Any idea??

Thanks!

**Comment by ihadeed** [comment]
Thanks, I will look into it soon.

**Comment by MarinoRaul** [comment]
Any resolution about this?

Thanks

**Comment by ihadeed** [comment]
I think it's because we're exporting `interface FileReader` and `declare var FileReader` at the same time. I will have to fix this in the Ionic Native repo. 

I'll work on it today.

**Comment by MarinoRaul** [comment]
Thanks! Please notify me when you commit this fix!

**Comment by ihadeed** [comment]
I can't reproduce this issue.

I tested it on the example project here: https://github.com/zyramedia/ionic-image-loader-example

I tried both `npm run build` and `npm run build --prod`. Didn't get any bundle issues.

**Comment by MarinoRaul** [comment]
I got this error with @ionic-native/core ... /device /file /transfer version 3.2.3 and image loader version 2.0.2

rollup failed: 'FileReader' is not exported by node_modules/@ionic-native/file/index.js 
[16:25:21]  ionic-app-script task: "build" 
[16:25:21]  Error: 'FileReader' is not exported by node_modules/@ionic-native/file/index.js 
Error: 'FileReader' is not exported by node_modules/@ionic-native/file/index.js


Any idea about this???????

THANKS A LOT!

**Comment by ihadeed** [comment]
As I mentioned earlier, I am not able to reproduce this issue.
