### ISSUE TITLE
Images flash when updating content

### ISSUE THREAD

**Issue by front-stream** [zyra/ionic-image-loader#33]
I am using pull to refresh functionality to refresh content. When I am updating content I see that all images are blank for very short time and after that they are loading from cache via file:// protocol. Is it possible to remove this effect?

**Comment by ihadeed** [comment]
When you're doing the refresh functionality, are you re-assigning the value of the `items` property? If so, then you are basically recreating the view and the image loader component is being recreated from scratch.

What you should do is:
```
class MyComponent {

  items: any[] = [];

  refresh() {
    this.getItems().then(items =>{ 
      if (this.items !== items) this.items = items;
    });
  }

}
```
