### ISSUE TITLE
dont run on wkwebview

### ISSUE THREAD

**Issue by HonLuk** [zyra/ionic-image-loader#37]
I use https://github.com/driftyco/cordova-plugin-wkwebview-engine ,and get warning 

ImageLoader Warning:  The cache system is not running. Images will be loaded by your browser instead.

according to https://github.com/driftyco/cordova-plugin-wkwebview-engine/commit/114a9b190a06285d3ae6ac0384e85e0401942d56

I can upload img by use fileUrl without file:// 

can anyone give me some info to run this plugin? thanks~!

**Comment by ihadeed** [comment]
Please update to the latest version `3.1.0`. It has a new approach for WKWebView. If the default configuration doesn't work for you, inject the configuration provider in your app's main module and run `imageLoaderConfig.setReturnType('base64');`.

**Comment by HonLuk** [comment]
@ihadeed thanks~! i will try
