### ISSUE TITLE
Custom spinner

### ISSUE THREAD

**Issue by finzaiko** [zyra/ionic-image-loader#38]
Can I Can add a little improvement for custom spinner style and color
https://ionicframework.com/docs/api/components/spinner/Spinner/
I need the color match to my base style
I can try to change on image-loader.ts
<Ion-spinner * ngIf = "&& spinner isLoading"> </ ion-spinner>
to this
<Ion-spinner * ngIf = "&& spinner isLoading" color = "primary" name = "dots"> </ ion-spinner>
still not working

**Comment by ihadeed** [comment]
I will publish a new release with this feature included sometime this weekend.

**Comment by finzaiko** [comment]
Great thanks

**Comment by Ross-Rawlins** [comment]
what is the correct way to create a custom spinner using a custom SVG? Do you just pass the SVG as a string in the name tag?
