### ISSUE TITLE
It work fine on Browser but in Android has permission error. 

### ISSUE THREAD

**Issue by hughred22** [zyra/ionic-image-loader#41]
Not allowed to load local resource: file:///data/user/0/org.creatorup.youtubebbwapp/cache/image-loader-cache/323897259

**Comment by hughred22** [comment]
It also does not load in iOs device. There is no error message but all the images are broken.

**Comment by ihadeed** [comment]
@hughred22 

- Did you follow the [installation steps](https://github.com/zyra/ionic-image-loader#installation)?
- What version of this module are you using?
- Is this issue with a fresh Ionic 2 project? or an older one?
- Can you provide steps to reproduce this issue?

**Comment by fermedina** [comment]
I have the same error when I run my app with -lc. But if I run my app without -lc it work fine.
I'm using version 3.2.1.

global packages:

    @ionic/cli-utils : 1.3.0
    Cordova CLI      : 6.5.0 
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.3.0
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Cordova Platforms               : android 6.1.2
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v7.7.4
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.0 
    ios-sim    : 5.0.10

**Comment by ihadeed** [comment]
@fermedina in live reload you can temporarily configure the module to return Base64 data instead of file URLs.
