### ISSUE TITLE
Not showing the image

### ISSUE THREAD

**Issue by tgensol** [zyra/ionic-image-loader#42]
Hi there,

I was using the 3.0.0 version but I was having this message for some images : 
`The cache system is not running. Images will be loaded by your browser instead.`

I tried to update to 3.1.0 and 3.1.1, but since then, I can see that the 'img-loader' got a "file//......." so I guess it is working, but the image is not displayed (and I see that the natural size of the image is 0x0 px), and " File Transfer Finished with response code 200".

Maybe I am missing something in the configuration ? (Like the File/File Transfer plugins ? I did the instructions but nothing more)

I am using angularjs4, ionic 3.0.1, and latest cordova.
My issue is on iOs simulator and iOs device.

Thanking you in advance

Regards

**Comment by ihadeed** [comment]
Could you please enable Debug Mode and let me know if you get any error messages? See https://github.com/zyra/ionic-image-loader#global-configuration for more information.

**Comment by hughred22** [comment]
I am having the same issue. But if you in global config turn the image into imageLoaderConfig.setImageReturnType('base64');. It will work.

**Comment by tgensol** [comment]
@hughred22  Thanks it is working very well ! I did set the debug mode, but I had no error message

**Comment by sofientouati** [comment]
same issue here but on android after updating from 3.0.1 to 3.1.0 and @hughred22 's solution not working it shows an corrupted image  for me when I load from  a URI

**Comment by hackeurtalibe** [comment]
@hughred22 you saved my day thx

**Comment by tgensol** [comment]
@hughred22 I just found that on Android 5.0.X, it is not working also (even with your fix). Do you have any idea ? thanks !

**Comment by zsomborbencsik** [comment]
bla
