### ISSUE TITLE
make contribution

### ISSUE THREAD

**Issue by msio777** [zyra/ionic-image-loader#43]
Hi,
I'd like to make contribution but I don't know how I can build this project locally and put into my own ionic project to test it. 
Could you give me a hint ?
Thanks :)

**Comment by ihadeed** [comment]
Hey @msio777 

You can build the project locally by running `npm run build`. Then you can copy the `dist` directory and replace it with the directory in your project `/node_modules/ionic-image-loader/dist/`.
