### ISSUE TITLE
Feature request: Add fallback support if src evaluates to null

### ISSUE THREAD

**Issue by uzumakinaruto123** [zyra/ionic-image-loader#57]
Consider image loader as

`<img-loader [src]="data?.avatar" useImg fallback="assets/img/placeholder.png"></img-loader>`

In some cases, this `avatar property` won't be set or would evaluate to `null`. Which won't set any src property on the image tag. 

For now, the fallback is only loaded when src has some random string or for actual URL which is 404.

When src is null, DOM looks like

```
<img-loader fallback="assets/img/placeholder.png" useimg="" _nghost-c0="" ng-reflect-fallback-url="assets/img/placeholder.png" ng-reflect-use-img=""><!--bindings={
  "ng-reflect-ng-if": "false"
}--><img _ngcontent-c0="" onerror="this.src=&quot;assets/img/placeholder.png&quot;"></img-loader>
```

If src is not set or evaluates to null, fallback src should be loaded.

Thanks!

**Comment by ihadeed** [comment]
Fixed in 4.1.1
