### ISSUE TITLE
Return image Url without the 'file://' prefix

### ISSUE THREAD

**Issue by anderloo** [zyra/ionic-image-loader#58]
Hi there, 

I am having to use WKWebview for my ionic 2 app, but I have learned that iOS really doesn't play well with the file:// prefix. Do you know of a way around this? 

I thought I had found a solution by preloading all the images and storing the returned url (minus the file://) in storage, but for some reason, most of the preloaded images are missing the next time I open the app.

I hope that makes sense. Can you help?

Thank you,

Andy

**Comment by ihadeed** [comment]
Are you using the latest version of this plugin? 

The latest version should fix all WKWebView issues as it replaces `file:///` with `http://localhost:8100/`

**Comment by anderloo** [comment]
Oh, how embarrassing. I was sure I had the latest version. But I didn't.

Thanks!!

Andy
