### ISSUE TITLE
Image not fetched from cache

### ISSUE THREAD

**Issue by robbannn** [zyra/ionic-image-loader#64]
Im lazy loading my pages in my Ionic application, and I wonder if I should use any different approach to be able to use ionic-image-loader because of that? I have followed the installation and usage documentation as is and I get some unexpected behaviour.

On one of my pages it works perfectly, but on another there is an XHR-request to fetch the image, even though the implementation is the same:
 `<img-loader *ngIf="imgSrc" [src]="imgSrc" [spinner]="true" useImg></img-loader>`

**Comment by ihadeed** [comment]
> XHR-request
Are you testing this on a browser?

**Comment by robbannn** [comment]
No on my Android device.

**Comment by ihadeed** [comment]
Is the XHR Request trying to fetch the image from the server? or from your local filesystem?

**Comment by robbannn** [comment]
From the server

**Comment by robbannn** [comment]
This is what it looks like in Chrome dev tools, when i remotely debug the app.

![prob](https://user-images.githubusercontent.com/7690889/27028645-ac4a3356-4f65-11e7-9326-f5c7951be91d.png)

**Comment by robbannn** [comment]
I found the problem. In my ngOnInit-function i was fetching the img URL remotely with firebase.storage().ref().getDownloadURL(). I made a change so that the URL was already there when entering the page.

Now its working splendidly!
Thanks for an awesome job and a fast response!
