### ISSUE TITLE
how to make the cache system is running?

### ISSUE THREAD

**Issue by watermelon-brother** [zyra/ionic-image-loader#70]
when I run in the brower,console have show some tip:
ImageLoader Warning: The cache system is not running. Images will be loaded by your browser instead.
instead when i use in the real ios device ,it not cache picture!
what can i do make this pluin success to use?

**Comment by ihadeed** [comment]
If you follow the instructions in this repo you should be ok. The module should work well if you aren't getting any console warnings on the device.

**Comment by watermelon-brother** [comment]
the plugin working is must in the real deavice?
I try in the browser,it's not working!simulator too! 
so,I can make a ipa to the real device and have a test?
I'm follow the instructions in this repo,and have test the example,but also not working in the browser!
what can i do to solve this problem? @ihadeed

**Comment by ihadeed** [comment]
It's not supposed to work in the browser.

**Comment by watermelon-brother** [comment]
but when I run in the ios 10.3 (iphone 7plus),it,s not working !
in the real device,first time I loading some picture in the APP,then I finished app,make offline,
and open APP again, picture is not loading from storage!how can I have test it?please give me some suggest! thank you! @ihadeed

**Comment by ihadeed** [comment]
@watermelon-brother Did you install the cordova plugins needed?

**Comment by watermelon-brother** [comment]
I had installed the plugins follow the repo,but I don,t know whether is successful.
what can I do to check it ? @ihadeed

**Comment by mahidis** [comment]
i have this similar issue . I've done the same steps as mentioned in installation steps . Even adding   <preference name="AndroidPersistentFileLocation" value="Internal" /> in config.xml  doesn't help. Please help!!

**Comment by fdambrosio** [comment]
Have you found the solution ?

**Comment by IgorSt** [comment]
why closed the issue? i've the same problem! Anybody have a solution ?
