### ISSUE TITLE
Feature Request: add watermark to specific image

### ISSUE THREAD

**Issue by caciobanita** [zyra/ionic-image-loader#72]

**Comment by cocowalla** [comment]
Got to say, I'm not a fan of this idea - it doesn't seem very relevant to this plugin. I'd prefer it stayed focussed on downloading and images, and 'core' features such as caching. Personally, I think watermarking belongs elsewhere.

**Comment by ihadeed** [comment]
As @cocowalla said, this plugin focuses on downloading/caching images. Adding watermarks sounds like an image manipulation functionality. 

You can create a directive and use `[img-loader]` as a selector. Then instruct the directive to append an element containing your watermark on top of the image. Few lines of TS/CSS would help you out here. This way if anyone takes a screenshot, there will be a watermark on the image.
