### ISSUE TITLE
Not working properly  with ChangeDetectionStrategy.OnPush

### ISSUE THREAD

**Issue by Daskus1** [zyra/ionic-image-loader#73]
I have a lot of custom components with `ChangeDetectionStrategy.OnPush`. I tried to use this component but the loading spinner is always shown, even if the image is loaded, the spinner still spinns above the loaded image.
If I remove `ChangeDetectionStrategy.OnPush` it works fine.

**Comment by ihadeed** [comment]
What version are you using?

The current version doesn't use OnPush strategy.

**Comment by Daskus1** [comment]
I am using the latest version.
Is there a way I make this component work in my OnPush components?

**Comment by pvdyck** [comment]
Confirmed, same problem here, not even with onPush strategy ... disabling spinner with [spinner]="false"  for now

**Comment by ihadeed** [comment]
@Daskus1 no, the component needs to have change detection active in order for it to work. I experimented with OnPush strategy before without success (issues with spinner). If your root component uses OnPush strategy, it affects the whole node tree.

@pvdyck did you experience this issue on `ionic serve` or on a device?

**Comment by pvdyck** [comment]
@ihadeed  on device / I use regular <img> outside of cordova

**Comment by ihadeed** [comment]
If a component/page uses OnPush strategy, change detection mechanism will only update the DOM if there's new data flowing from the top. `img-loader` component updates itself based on the data coming from the provider.

The only way this might work is if you preload your images and only render the `img-loader` component when the images are ready in the filesystem.
