### ISSUE TITLE
breaking in ionic-native 4.0.0

### ISSUE THREAD

**Issue by dmastag** [zyra/ionic-image-loader#74]
ionic-native 4.0.0 changed @ionic-native/transfer into @ionic-native/file-transfer and this breaks ionic-image-loader

**Comment by ihadeed** [comment]
Thanks! I will update this soon.

**Comment by ihadeed** [comment]
Please update to `ionic-image-loader@4.0.0`

**Comment by dmastag** [comment]
Whoaa, that was fast. Thanks!
