### ISSUE TITLE
Error since last update (v.4.0.0)

### ISSUE THREAD

**Issue by mtshare** [zyra/ionic-image-loader#75]
Hi, after updating this plugin to v.4.0.0 and all @ionic-native to v4 it's stopped working.

Here the error:
`Uncaught (in promise): cordova_not_available`

Any suggestions?
Thanks.

**Comment by ihadeed** [comment]
Thanks, I'll take a look soon.

**Comment by mtshare** [comment]
The problem is still present in the last update :(

**Comment by ihadeed** [comment]
Fixed in 4.1.0
