### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by YasirPanjsheri** [zyra/ionic-image-loader#76]
hi, I keep receiving this error `Cannot read property 'length' of undefined
    at ImageLoader.hashString (file:///android_asset/www/build/main.js:64716:19)` 
this is how I am using it: ` <img-loader class="profileImg" [src]="selectedImage" useImg></img-loader>`
I also added in constructor a fallback config: `this.imageLoaderConfig.setFallbackUrl('assets/images/emptyImg.png');` 

the app does not crash... it picks the image and displays it without problem... but in log this error always appears when the page loads... do I have to worry about this ?

**Comment by ihadeed** [comment]
Probably there is an issue with the image URL you are passing. Just pushed a fix to reject any invalid links. This will cause the component to use the fallback URL immediately.
