### ISSUE TITLE
Not working on Browser

### ISSUE THREAD

**Issue by dmastag** [zyra/ionic-image-loader#77]
After some debugging it seems that the following line in src\providers\image-loader.ts is never called on the Browser

```Observable.fromEvent(document, 'deviceready').first().subscribe(function (res) {```

**Comment by ihadeed** [comment]
Browser as in Cordova Browser or `ionic serve`?

**Comment by dmastag** [comment]
ionic serve

**Comment by ihadeed** [comment]
Hmm, good call. I think we need to go back to `platform.ready()`. Or maybe add something like:
```ts
if (!platform.is('cordova')) {
  this.init = true;
} else {
  Observable.fromEvent(....);
}
```

**Comment by dmastag** [comment]
That seems more in line of what Ionic does, let me try to submit a PR

**Comment by ihadeed** [comment]
Just released 4.0.1 with your fix included.

**Comment by danielehrhardt** [comment]
Please Reopen the Issue i get the Error Message with v4.0.1
`Uncaught (in promise): cordova_not_available`

**Comment by ihadeed** [comment]
Sorry I just realized this whole thing is because of #61 ... I didn't review the PR properly. Reverting now.

**Comment by danielehrhardt** [comment]
Thank you for the fast Help 👍
