### ISSUE TITLE
Does not work in ionic cordova emulate ios --livereload

### ISSUE THREAD

**Issue by leoiii12** [zyra/ionic-image-loader#80]
![screen shot 2017-07-18 at 1 13 07 pm](https://user-images.githubusercontent.com/13096791/28301652-ea4cf596-6bba-11e7-8e3c-2a8eaab18f3e.png)

**Comment by ihadeed** [comment]
Is this a livereload issue?

Configure the module to return Base64 images instead of file URIs

**Comment by leoiii12** [comment]
The issue is caused by using Livereload and WKWebView together.

**Comment by ihadeed** [comment]
What version are you using? Also which WKWebView (original or Ionic fork)?

The module is designed to handle WKWebView and other iOS issues. The only issues you might face  will be when you are running on live reload. That's when you have to temporarily use the Base64 option.

**Comment by leoiii12** [comment]
- 4.1.1
- Ionic fork

The function isIonicWKWebView will return false when using both Livereload and WKWebView.
