### ISSUE TITLE
Image never loads and fallback doesn't come

### ISSUE THREAD

**Issue by iowaz** [zyra/ionic-image-loader#85]
Hi there!

I have a ion-item with a ion-avatar, inside it a use the ionic-image-loader like that:

`<img-loader src="{{ item.product.image.url }}" fallback="./assets/icon/icon-black.jpg" useImg></img-loader>`

But the image never loads and the spinner goes on infinitly.

I have set the debugmode, but doesn't show any kinda of error/warning in the console.

![alt text](http://i.imgur.com/s3n4mZo.png "DOM")

The DOM is generated by a ngFor, and that is where the img url comes from:

>{  
            "relation_id":291,
            "user_buyer_id":null,
            "quantity":0.16,
            "price_paid":21.9,
            "product":{  
               "product_id":7689,
               "category_id":737,
               "name":"PRESUNTO",
               "description":null,
               "image":{  
                  **"url":"https:\/\/homelist.orangepixel.com.br\/photo\/5021475f7fa7ff6e63264e10f26e518b.jpeg\/a",
                  "md5":"5021475f7fa7ff6e63264e10f26e518b"**
               },
               "icon_css":null,
               "is_specific":false,
               "is_fractional":false,
            }
         },

PS: the url have escape tags, so it comes like this:
![alt text](http://i.imgur.com/cro654l.png "JSON")

Anyone knows a solution?

thanks ;)

**Comment by iowaz** [comment]
Nevermind, it works if you use --prod... Strange since I wasn't using livereload (if you use the plugin throws a warning and fallbacks), sometimes I just rather compile faster but without livereload.

If it's possible, throw the same warning for livereload if you just use "ionic run/emulate android --target=######".

Thanks again ;)

**Comment by ihadeed** [comment]
Can you replace your HTML with this:
```html
<img-loader [src]="item.product.image.url" fallback="./assets/icon/icon-black.jpg" useImg></img-loader>
```

**Comment by gklasen** [comment]
This still is a problem.
