### ISSUE TITLE
Images don't load after adding cordova-google-maps plugin

### ISSUE THREAD

**Issue by spencerevison** [zyra/ionic-image-loader#86]
First off, thank you so much for creating this plugin! It has helped immensely and I have not run into any issues until now.

It seems that the cordova-google-maps plugin is interfering with the loading of images.

ionic-image-loader is loading images as expected, but after adding the cordova-google-maps plugin, the images no longer load. Enabling debug-mode produces this error in the console: 
`ImageLoader Error: 
FileTransferError
body: null
code: 3
exception: null
http_status: null
source: "assets/img/events/rock/branding/card.jpg"
target: "file:///Users/...`

After removing the cordova-google-maps plugin, images load again as expected.

**Comment by curlybracketsSARL** [comment]
Same issue, have you found any fixes for this?

**Comment by dembal1990** [comment]
+1 ,but for me with cordova-plugin-googleplus

**Comment by ihadeed** [comment]
Does this issue occur just by simply installing google-maps/google-plus plugins? or does it only happen when using the other plugins within the same component/page?
