### ISSUE TITLE
Causes issue with ion-slides

### ISSUE THREAD

**Issue by MishRanu** [zyra/ionic-image-loader#97]
Good work, but the use of this library seems to cause an issue with ion-slides. On including it, when i swipe the slides I get a extra white slide, and the slider stops working. (Please note that I also use google maps in my app, if that is useful). I also tried with img tag, and the issue still existed, until I removed this from the code. 
Apart from that sometimes the image gets corrupted and only half of it loads. Such things would be unacceptable in a production app.

**Comment by emrahcetiner** [comment]
I have exactly the same problem

**Comment by bhavincb** [comment]
is there any workaround for image corruption?

**Comment by ihadeed** [comment]
This should be fixed in the latest release. If you're still experiencing issues, please open a new issues with steps to reproduce.
