### ISSUE TITLE
Not compatible with Ionic View

### ISSUE THREAD

**Issue by DODMax** [zyra/ionic-image-loader#99]
Seems like the fallback image is always used on Ionic view.
Or maybe any way to simply disable the plugin (like in browser) via global config?

**Comment by ianrothmann** [comment]
Ionic view does not support the File and Filetransfer ionic native plugins.

**Comment by DODMax** [comment]
Agreed but it should at least behave like in the browser no?

**Comment by ianrothmann** [comment]
I see what you mean now. It is not right. I'm using [fallback] as a workaround at this stage, not optimal but anyway.
